<!doctype html>

<html lang="en">

<head>

<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="bootstrap/css/bootstrap.css">

<title>Why and What is MLM?</title>

<style>
	
	.account-wall
	{
		background-color: #DCDCDC;
    	-moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    	-webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
    	box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
	}

</style>

</head>

<body>

<div class="row">
		

<div class="container-fluid">
	
		<?php
		
			include("header.php");
		
		?>
     <div class="col-sm-12">

            <center><div class="col-sm-6">

				<h3 class="text-center" style="padding-top: 1%; padding-bottom: 1%;"><b>What is MLM?</b></h3>

				<p class="card-text">Multi Level Marketing, or MLM, is a system for selling goods or services
                        through a network of distributors. Multilevel marketing is also referred to as
                        Network Marketing or Direct Sales.
                        Also known as, Network Marketing….Blockchain…..Direct Sale marketing.
                        Multi Level marketing works through recruitment. You are invited to become a
                        distributor, sometimes through another distributor of the company’s product and
                        sometimes though generally advertised meetings.
                        <p class="card-text">

                        If you become a distributor with a direct selling company, you will earn with both
                        by selling the products and also by the income generated by distributor under
                        you and distributor under you will recruit another distributor to earn more.
                        Distributor that you sign in with your Multi level marketing plan and ones they are
                        signed up they are called as downline.
                        </p>
                        </p>
			</div>

            <div class="col-sm-6">
				
				<h3 class="text-center" style="padding-top: 1%; padding-bottom: 1%;"><b>Why MLM?</b></h3>
                
				<p class="card-text">Probably because most Multilevel Marketing programs operate on a "the sky's
                        the limit" promise with a nice bit of "easy money" thrown in. If you work hard, the
                        MLM sales pitch says, there's no limit to how much money you could make. And
                        through your downline you will actually make money doing nothing.
                        <p class="card-text">
                        The cherry on top is that MLMs are usually very inexpensive to join, so becoming
                        a distributor is much cheaper than starting a business of your own in many cases
                        or doing something like buying into a franchise.
                        Plus, many Multi Level Marketing programs are carefully constructed with
                        attractive rewards. Avon representatives can earn trips to vacation destinations.
                        Amway offers cash bonuses based on performance each month. And who
                        doesn't remember the pink convertibles awarded to top selling Mary Kay
                        consultants.
                        </p>
                        </p>
			    </div></center>

             </div>   		


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

<script src="bootstrap/js/bootstrap.js"></script>

</body>

</html>    